-- Compare results with previous version of db

SELECT ZnoYear
	  ,[CompositeRank]
      ,[IT_CompositeRank]
      ,[TotalRank]
      ,[MedTotalRank]
      ,[IT_Rank]
      ,[UmlRank]
      ,[MathRank]
      ,[PhysRank]
      ,[EngRank]
      ,[HistRank]
      ,[ChemRank]
      ,[BioRank]
      ,[AvgScore]
      ,[MedScore]
      ,REPLACE(REPLACE(REPLACE(REPLACE([EOName], '"', ''), '''', ''), '-', ''), ' ', '') [EOName]
      ,[EOAreaFullName]
      ,[Examinees]
      ,[FailedExams]
      ,[PassRate]
      ,[StdDevScore]
      ,[IT_AvgScore]
      ,[UmlAvg]
      ,[UmlStDev]
      ,[UmlMed]
      ,[UmlN]
      ,[HistAvg]
      ,[HistStDev]
      ,[HistMed]
      ,[HistN]
      ,[MathAvg]
      ,[MathStDev]
      ,[MathMed]
      ,[MathN]
      ,[PhysAvg]
      ,[PhysStDev]
      ,[PhysMed]
      ,[PhysN]
      ,[ChemAvg]
      ,[ChemStDev]
      ,[ChemMed]
      ,[ChemN]
      ,[BioAvg]
      ,[BioStDev]
      ,[BioMed]
      ,[BioN]
      ,[GeoAvg]
      ,[GeoStDev]
      ,[GeoMed]
      ,[GeoN]
      ,[EngAvg]
      ,[EngStDev]
      ,[EngMed]
      ,[EngN]
      ,[FrAvg]
      ,[FrStDev]
      ,[FrMed]
      ,[FrN]
      ,[DeuAvg]
      ,[DeuStDev]
      ,[DeuMed]
      ,[DeuN]
      ,[SpAvg]
      ,[SpStDev]
      ,[SpMed]
      ,[SpN]
      ,[RusAvg]
      ,[RusStDev]
      ,[RusMed]
      ,[RusN]
      ,[EOTypeName]
      ,[TerType]
      ,[IsPrivate]
      --,[EOHash]
      --,[EOHash_Merge]
      ,[TotalRank_D]
      ,[MedTotalRank_D]
      ,[IT_Rank_D]
      ,[UmlRank_D]
      ,[MathRank_D]
      ,[PhysRank_D]
      ,[EngRank_D]
      ,[HistRank_D]
      ,[ChemRank_D]
      ,[BioRank_D]
FROM
(SELECT 2016 ZnoYear, *
  FROM [znodb].[zno2016].[SchoolRating_Composite_3Y]
  UNION ALL
SELECT 2017 ZnoYear,*
  FROM [znodb].[zno2017].[SchoolRating_Composite_3Y]
  UNION ALL
SELECT 2018 ZnoYear,*
  FROM [znodb].[zno2018].[SchoolRating_Composite_3Y]
UNION ALL
SELECT 2019 ZnoYear,*
  FROM [znodb].[zno2019].[SchoolRating_Composite_3Y]) C
EXCEPT 
SELECT ZnoYear
	  ,[CompositeRank]
      ,[IT_CompositeRank]
      ,[TotalRank]
      ,[MedTotalRank]
      ,[IT_Rank]
      ,[UmlRank]
      ,[MathRank]
      ,[PhysRank]
      ,[EngRank]
      ,[HistRank]
      ,[ChemRank]
      ,[BioRank]
      ,[AvgScore]
      ,[MedScore]
      ,REPLACE(REPLACE(REPLACE(REPLACE([EOName], '"', ''), '''', ''), '-', ''), ' ', '') [EOName]
      ,[EOAreaFullName]
      ,[Examinees]
      ,[FailedExams]
      ,[PassRate]
      ,[StdDevScore]
      ,[IT_AvgScore]
      ,[UmlAvg]
      ,[UmlStDev]
      ,[UmlMed]
      ,[UmlN]
      ,[HistAvg]
      ,[HistStDev]
      ,[HistMed]
      ,[HistN]
      ,[MathAvg]
      ,[MathStDev]
      ,[MathMed]
      ,[MathN]
      ,[PhysAvg]
      ,[PhysStDev]
      ,[PhysMed]
      ,[PhysN]
      ,[ChemAvg]
      ,[ChemStDev]
      ,[ChemMed]
      ,[ChemN]
      ,[BioAvg]
      ,[BioStDev]
      ,[BioMed]
      ,[BioN]
      ,[GeoAvg]
      ,[GeoStDev]
      ,[GeoMed]
      ,[GeoN]
      ,[EngAvg]
      ,[EngStDev]
      ,[EngMed]
      ,[EngN]
      ,[FrAvg]
      ,[FrStDev]
      ,[FrMed]
      ,[FrN]
      ,[DeuAvg]
      ,[DeuStDev]
      ,[DeuMed]
      ,[DeuN]
      ,[SpAvg]
      ,[SpStDev]
      ,[SpMed]
      ,[SpN]
      ,[RusAvg]
      ,[RusStDev]
      ,[RusMed]
      ,[RusN]
      ,[EOTypeName]
      ,[TerType]
      ,[IsPrivate]
      --,[EOHash]
      --,[EOHash_Merge]
      ,[TotalRank_D]
      ,[MedTotalRank_D]
      ,[IT_Rank_D]
      ,[UmlRank_D]
      ,[MathRank_D]
      ,[PhysRank_D]
      ,[EngRank_D]
      ,[HistRank_D]
      ,[ChemRank_D]
      ,[BioRank_D] FROM
(SELECT 2016 ZnoYear
	  ,NULL [CompositeRank]
      ,NULL [IT_CompositeRank]
      ,[TotalRank]
      ,[MedTotalRank]
      ,[IT_Rank]
      ,[UmlRank]
      ,[MathRank]
      ,[PhysRank]
      ,[EngRank]
      ,[HistRank]
      ,[ChemRank]
      ,[BioRank]
      ,[AvgScore]
      ,[MedScore]
      ,[EOName]
      ,[EOAreaFullName]
      ,[Examinees]
      ,[FailedExams]
      ,[PassRate]
      ,[StdDevScore]
      ,[IT_AvgScore]
      ,[UmlAvg]
      ,[UmlStDev]
      ,[UmlMed]
      ,[UmlN]
      ,[HistAvg]
      ,[HistStDev]
      ,[HistMed]
      ,[HistN]
      ,[MathAvg]
      ,[MathStDev]
      ,[MathMed]
      ,[MathN]
      ,[PhysAvg]
      ,[PhysStDev]
      ,[PhysMed]
      ,[PhysN]
      ,[ChemAvg]
      ,[ChemStDev]
      ,[ChemMed]
      ,[ChemN]
      ,[BioAvg]
      ,[BioStDev]
      ,[BioMed]
      ,[BioN]
      ,[GeoAvg]
      ,[GeoStDev]
      ,[GeoMed]
      ,[GeoN]
      ,[EngAvg]
      ,[EngStDev]
      ,[EngMed]
      ,[EngN]
      ,[FrAvg]
      ,[FrStDev]
      ,[FrMed]
      ,[FrN]
      ,[DeuAvg]
      ,[DeuStDev]
      ,[DeuMed]
      ,[DeuN]
      ,[SpAvg]
      ,[SpStDev]
      ,[SpMed]
      ,[SpN]
      ,[RusAvg]
      ,[RusStDev]
      ,[RusMed]
      ,[RusN]
      ,[EOTypeName]
      ,[TerType]
      ,[IsPrivate]
      ,[EOHash]
      ,[EOHash_Merge]
      ,NULL [TotalRank_D]
      ,NULL [MedTotalRank_D]
      ,NULL [IT_Rank_D]
      ,NULL [UmlRank_D]
      ,NULL [MathRank_D]
      ,NULL [PhysRank_D]
      ,NULL [EngRank_D]
      ,NULL [HistRank_D]
      ,NULL [ChemRank_D]
      ,NULL [BioRank_D]
  FROM [znodb_2019].[zno2016].[SchoolRating]
UNION ALL
SELECT 2017 ZnoYear, *
  FROM [znodb_2019].[zno2017].[SchoolRating_Composite_2Y]
  UNION ALL
SELECT 2018 ZnoYear, *
  FROM [znodb_2019].[zno2018].[SchoolRating_Composite_3Y]
UNION ALL
SELECT 2019 ZnoYear, *
  FROM [znodb_2019].[zno2019].[SchoolRating_Composite_3Y]) P
