-- input variables: ZnoYear
EXEC ('DROP VIEW IF EXISTS [zno$(ZnoYear)].[SchoolRating_Composite_3Y]')
GO

CREATE VIEW [zno$(ZnoYear)].[SchoolRating_Composite_3Y] AS
SELECT  TOP 1000000
	   [CompositeRank]
	  ,[IT_CompositeRank]
      ,[CompositeAvgScore]
	  ,[IT_CompositeAvgScore]
	  ,TotalRank
	  ,MedTotalRank
	  ,IT_Rank     
      ,UmlRank
      ,UkrRank
      ,MathRank
      ,PhysRank
      ,EngRank
	  ,HistRank
      ,ChemRank
      ,BioRank 
	  ,[AvgScore]
	  ,[MedScore]
	  ,[EOName]
	  ,[EOAreaFullName]
	  ,[Examinees]
	  ,[FailedExams]
	  ,[PassRate]
	  ,[StdDevScore]
	  ,[IT_AvgScore]
      ,[UmlAvg]
	  ,[UmlStDev]
	  ,[UmlMed]
	  ,[UmlN]
      ,[UkrAvg]
	  ,[UkrStDev]
	  ,[UkrMed]
	  ,[UkrN]
	  ,[HistAvg]
	  ,[HistStDev]
	  ,[HistMed]
	  ,[HistN]
	  ,[MathAvg]
	  ,[MathStDev]
	  ,[MathMed]
	  ,[MathN]
	  ,[PhysAvg]
	  ,[PhysStDev]
	  ,[PhysMed]
	  ,[PhysN]
	  ,[ChemAvg]
	  ,[ChemStDev]
	  ,[ChemMed]
	  ,[ChemN]
	  ,[BioAvg]
	  ,[BioStDev]
	  ,[BioMed]
	  ,[BioN]
	  ,[GeoAvg]
	  ,[GeoStDev]
	  ,[GeoMed]
	  ,[GeoN]
	  ,[EngAvg]
	  ,[EngStDev]
	  ,[EngMed]
	  ,[EngN]
	  ,[FrAvg]
	  ,[FrStDev]
	  ,[FrMed]
	  ,[FrN]
	  ,[DeuAvg]
	  ,[DeuStDev]
	  ,[DeuMed]
	  ,[DeuN]
	  ,[SpAvg]
	  ,[SpStDev]
	  ,[SpMed]
	  ,[SpN]
	  ,[RusAvg]
	  ,[RusStDev]
	  ,[RusMed]
	  ,[RusN]
	  ,[EOTypeName]
	  ,[TerType]
	  ,[IsPrivate]
	  ,[EOHash]
	  ,[EOHash_Merge]
	  ,[CompositeRank_D]
	  ,[IT_CompositeRank_D] 
	  ,[TotalRank_D]	
      ,[MedTotalRank_D]
      ,[IT_Rank_D]				
      ,[UmlRank_D]			
      ,[UkrRank_D]			
      ,[MathRank_D]	
      ,[PhysRank_D]	
      ,[EngRank_D]			
      ,[HistRank_D]	
      ,[ChemRank_D]	
      ,[BioRank_D]		
	  , SortOrder
FROM 
	[dbo].[SchoolRating_Composite_3Y]
WHERE [ZnoYear] = $(ZnoYear)
ORDER BY SortOrder
	