CREATE TABLE [dbo].[SchoolRatingShort](
	[ZnoYear] [int] NOT NULL,
	[TotalRank] [bigint] NULL,
	[MedTotalRank] [bigint] NULL,
	[IT_Rank] [bigint] NULL,
	[UmlRank] [bigint] NULL,
	[UkrRank] [bigint] NULL,
	[MathRank] [bigint] NULL,
	[PhysRank] [bigint] NULL,
	[EngRank] [bigint] NULL,
	[HistRank] [bigint] NULL,
	[ChemRank] [bigint] NULL,
	[BioRank] [bigint] NULL,
	[AvgScore] [decimal](38, 6) NULL,
	[MedScore] [float] NULL,
	[Examinees] [int] NULL,
	[FailedExams] [int] NULL,
	[PassRate] [numeric](25, 12) NULL,
	[StdDevScore] [float] ,
	[IT_AvgScore] [numeric](38, 6) NULL,
	[UmlAvg] [decimal](38, 6) NULL,
	[UmlStDev] [float] NULL,
	[UmlMed] [float] NULL,
	[UmlN] [int] NULL,
	[UkrAvg] [decimal](38, 6) NULL,
	[UkrStDev] [float] NULL,
	[UkrMed] [float] NULL,
	[UkrN] [int] NULL,
	[HistAvg] [decimal](38, 6) NULL,
	[HistStDev] [float] NULL,
	[HistMed] [float] NULL,
	[HistN] [int] NULL,
	[MathAvg] [decimal](38, 6) NULL,
	[MathStDev] [float] NULL,
	[MathMed] [float] NULL,
	[MathN] [int] NULL,
	[PhysAvg] [decimal](38, 6) NULL,
	[PhysStDev] [float] NULL,
	[PhysMed] [float] NULL,
	[PhysN] [int] NULL,
	[ChemAvg] [decimal](38, 6) NULL,
	[ChemStDev] [float] NULL,
	[ChemMed] [float] NULL,
	[ChemN] [int] NULL,
	[BioAvg] [decimal](38, 6) NULL,
	[BioStDev] [float] NULL,
	[BioMed] [float] NULL,
	[BioN] [int] NULL,
	[GeoAvg] [decimal](38, 6) NULL,
	[GeoStDev] [float] NULL,
	[GeoMed] [float] NULL,
	[GeoN] [int] NULL,
	[EngAvg] [decimal](38, 6) NULL,
	[EngStDev] [float] NULL,
	[EngMed] [float] NULL,
	[EngN] [int] NULL,
	[FrAvg] [decimal](38, 6) NULL,
	[FrStDev] [float] NULL,
	[FrMed] [float] NULL,
	[FrN] [int] NULL,
	[DeuAvg] [decimal](38, 6) NULL,
	[DeuStDev] [float] NULL,
	[DeuMed] [float] NULL,
	[DeuN] [int] NULL,
	[SpAvg] [decimal](38, 6) NULL,
	[SpStDev] [float] NULL,
	[SpMed] [float] NULL,
	[SpN] [int] NULL,
	[RusAvg] [decimal](38, 6) NULL,
	[RusStDev] [float] NULL,
	[RusMed] [float] NULL,
	[RusN] [int] NULL,
	[EOHash] [varbinary](20) NOT NULL,
	[EOHash_Merge] [varbinary](20) NOT NULL, 
    [SortOrder] INT NOT NULL
) ON [PRIMARY];
GO

CREATE INDEX [UK_SchoolRatingShort_EOHash_Merge]   
    ON [dbo].[SchoolRatingShort] (EOHash_Merge) 
GO

CREATE UNIQUE INDEX [UK_SchoolRatingShort_ZnoYear_EOHash]   
    ON [dbo].[SchoolRatingShort] (ZnoYear, EOHash) 
GO
CREATE UNIQUE INDEX [UK_SchoolRatingShort_ZnoYear_EOHash_Merge]   
    ON [dbo].[SchoolRatingShort] (ZnoYear, EOHash_Merge) 
GO

